export const colors = {
  background: 0x020307,
  grid: 0x234a55,
  gridAccent: 0x4bc9d9,
  coreFill: 0x06181c,
  coreStroke: 0x8ff6ff,
  enemyStroke: 0xff6f91,
  enemyFill: 0x200811,
  enemyCore: 0xffd1dc,
  expStroke: 0xb7ff74,
  expFill: 0x172b08,
  particle: 0xffd166,
  expTrail: 0xc8ff91,
  pulse: 0xa8fbff,
  pulseAccent: 0x4bc9d9,
  text: '#d8fbff',
  mutedText: '#7fb6bf',
  overlayFill: 0x020307,
  overlayPanel: 0x06181c,
} as const;

export const gameplayConfig = {
  core: {
    radius: 10,
    outerRadius: 18,
  },
  player: {
    collisionRadius: 10,
    maxHp: 5,
    speed: 240,
    invincibilityMs: 900,
    damageFlashMs: 140,
    trailLifeMs: 280,
    trailAlpha: 0.28,
  },
  grid: {
    spacing: 32,
  },
  world: {
    width: 2400,
    height: 1600,
  },
  enemy: {
    radius: 12,
    healthMin: 1,
    healthMax: 3,
    spawnIntervalMs: 1050,
    spawnPadding: 48,
    speedMin: 34,
    speedMax: 58,
    speedGrowthPerSecond: 0.005,
    speedMaxMultiplier: 3,
    removeRadius: 30,
    maxEnemies: 250,
    spawnDistanceMin: 520,
    spawnDistanceMax: 760,
    bossSpawnIntervalMs: 2500,
    bossSpawnCount: 2,
    bossSpawnEnemyType: 'small',
    maxSpawnedChildrenPerBoss: 20,
    types: [
      {
        id: 'small',
        hp: 1,
        speedMultiplier: 1.35,
        radius: 10,
        damageToPlayer: 1,
        expValue: 1,
        spawnWeight: 55,
        strokeColor: 0xff7aa2,
        fillColor: 0x200811,
        coreColor: 0xffd1dc,
        sides: 3,
      },
      {
        id: 'normal',
        hp: 2,
        speedMultiplier: 1,
        radius: 13,
        damageToPlayer: 1,
        expValue: 2,
        spawnWeight: 30,
        strokeColor: 0xff6f91,
        fillColor: 0x200811,
        coreColor: 0xffd1dc,
        sides: 4,
      },
      {
        id: 'heavy',
        hp: 5,
        speedMultiplier: 0.65,
        radius: 18,
        damageToPlayer: 2,
        expValue: 5,
        spawnWeight: 12,
        strokeColor: 0xffd166,
        fillColor: 0x24180a,
        coreColor: 0xffe3a3,
        sides: 6,
      },
      {
        id: 'tank',
        hp: 10,
        speedMultiplier: 0.4,
        radius: 24,
        damageToPlayer: 3,
        expValue: 12,
        spawnWeight: 3,
        strokeColor: 0xb993ff,
        fillColor: 0x151024,
        coreColor: 0xe1d2ff,
        sides: 8,
      },
      {
        id: 'boss',
        hp: 30,
        speedMultiplier: 0.28,
        radius: 32,
        damageToPlayer: 3,
        expValue: 30,
        spawnWeight: 1,
        strokeColor: 0xfff6a8,
        fillColor: 0x241f08,
        coreColor: 0xffffff,
        sides: 8,
      },
    ],
  },
  expOrb: {
    radius: 6,
    value: 1,
    baseMagnetRadius: 80,
    magnetSpeed: 360,
    terminalAccelerationDistance: 170,
    terminalAccelerationMultiplier: 1.1,
    terminalAccelerationPower: 2,
    collectRadius: 18,
  },
  pulse: {
    baseRadius: 110,
    chargeRadiusMultiplier: 280 / 110,
    minDamage: 1,
    maxDamage: 3,
    maxChargeMs: 1100,
    durationMs: 280,
    strokeWidth: 2,
  },
  shockwave: {
    damage: 1,
  },
  score: {
    enemiesDefeated: 10,
    expCollected: 1,
    maxCombo: 20,
    levelReached: 100,
    playTimeSecond: 2,
  },
  combo: {
    graceMs: 2200,
    shakeDurationMs: 90,
    screenShakeStrength: 0.0035,
    shakeStepEvery: 10,
    shakeIntensityStep: 0.001,
    maxShakeIntensity: 0.009,
    slowMotionEvery: 50,
    slowMotionDurationMs: 420,
    slowMotionScale: 0.35,
  },
  progression: {
    baseExpToNextLevel: 8,
    expGrowthPerLevel: 5,
  },
  upgrades: {
    pulseRadiusMultiplier: 1.2,
    orbMagnetMultiplier: 1.3,
    comboGraceBonusMs: 1500,
    pulseDamageBonus: 1,
    shockwaveComboBonusPerComboBonus: 0.005,
    playerSpeedMultiplier: 1.12,
    maxHpBonus: 1,
    healAmount: 1,
  },
  combatTuning: {
    pulseAngleInitialDegrees: 30,
    pulseAngleUpgradeAmountDegrees: 5,
    shockwaveBaseRadius: 48,
    shockwaveRadiusUpgradeAmount: 6,
    comboShockwaveRadiusBonusPerCombo: 0.025,
    maxShockwaveRadiusMultiplier: 2.75,
    maxShockwaveChainPerPulse: 50,
  },
  hud: {
    titleVisibleMs: 3000,
    titleFadeMs: 520,
    comboPopScale: 1.16,
    comboPopDurationMs: 115,
  },
  levelUp: {
    backdropAlpha: 0.9,
    panelAlpha: 0.96,
    optionFillAlpha: 0.68,
    optionStrokeAlpha: 0.58,
  },
  effects: {
    maxParticles: 260,
    enemyBurstParticles: 10,
    enemyBurstSpeedMin: 120,
    enemyBurstSpeedMax: 290,
    enemyBurstLifeMs: 330,
    enemyShardAlpha: 0.72,
    enemyFlashDurationMs: 75,
    enemyFlashScale: 1.22,
    enemyFlashFillAlpha: 0.52,
    enemyFlashStrokeAlpha: 0.94,
    maxTrailSegments: 180,
    orbTrailLifeMs: 210,
    coreAbsorbGlowDurationMs: 145,
    coreAbsorbGlowRadius: 48,
    coreAbsorbGlowAlpha: 0.36,
    coreAbsorbGlowScale: 1.45,
    pulseRingDurationMs: 420,
    pulseRingDurationStepMs: 20,
    pulseEchoDelayMs: 32,
    pulseRingAlpha: 0.38,
    pulseRingChargeAlpha: 0.12,
    pulseRingAlphaStep: 0.07,
    pulseRingInnerAlphaMultiplier: 0.45,
    pulseRingRadiusStep: 14,
    pulseRingStartStep: 8,
    pulseRingWidthChargeBoost: 1.3,
    shockwaveRingDurationMs: 360,
    shockwaveRingAlpha: 0.52,
    shockwaveRingWidth: 2,
    shockwaveRingGlowAlpha: 0.08,
    shockwaveRingInnerAlphaMultiplier: 0.58,
    shockwaveRingSpokeAlphaMultiplier: 0.42,
    shockwaveRingSpokeCount: 8,
  },
} as const;
