export const colors = {
  background: 0x020307,
  grid: 0x234a55,
  gridAccent: 0x4bc9d9,
  coreFill: 0x06181c,
  coreStroke: 0x8ff6ff,
  enemyStroke: 0xff6f91,
  enemyFill: 0x200811,
  enemyCore: 0xffd1dc,
  expStroke: 0xb7ff74,
  expFill: 0x172b08,
  particle: 0xffd166,
  expTrail: 0xc8ff91,
  pulse: 0xa8fbff,
  pulseAccent: 0x4bc9d9,
  text: '#d8fbff',
  mutedText: '#7fb6bf',
  overlayFill: 0x020307,
  overlayPanel: 0x06181c,
} as const;

export const gameplayConfig = {
  core: {
    radius: 36,
    outerRadius: 54,
  },
  grid: {
    spacing: 32,
  },
  enemy: {
    radius: 12,
    healthMin: 1,
    healthMax: 3,
    spawnIntervalMs: 1050,
    spawnPadding: 48,
    speedMin: 34,
    speedMax: 58,
    removeRadius: 30,
  },
  expOrb: {
    radius: 6,
    value: 1,
    magnetSpeed: 360,
    terminalAccelerationDistance: 170,
    terminalAccelerationMultiplier: 1.1,
    terminalAccelerationPower: 2,
    collectRadius: 18,
  },
  pulse: {
    baseRadius: 110,
    chargeRadiusMultiplier: 280 / 110,
    minDamage: 1,
    maxDamage: 3,
    maxChargeMs: 1100,
    durationMs: 280,
    strokeWidth: 2,
  },
  shockwave: {
    damage: 1,
  },
  combo: {
    graceMs: 2200,
    shakeDurationMs: 90,
    screenShakeStrength: 0.0035,
    shakeStepEvery: 10,
    shakeIntensityStep: 0.001,
    maxShakeIntensity: 0.009,
    slowMotionEvery: 50,
    slowMotionDurationMs: 420,
    slowMotionScale: 0.35,
  },
  progression: {
    baseExpToNextLevel: 8,
    expGrowthPerLevel: 5,
  },
  upgrades: {
    pulseRadiusMultiplier: 1.2,
    orbMagnetMultiplier: 1.3,
    comboGraceBonusMs: 1500,
  },
  combatTuning: {
    pulseAngleInitialDegrees: 30,
    pulseAngleUpgradeAmountDegrees: 5,
    shockwaveBaseRadius: 36,
    shockwaveRadiusUpgradeAmount: 4,
    comboShockwaveRadiusBonusPerCombo: 0.02,
    maxShockwaveRadiusMultiplier: 2.5,
    maxShockwaveChainPerPulse: 50,
  },
  hud: {
    titleVisibleMs: 3000,
    titleFadeMs: 520,
    comboPopScale: 1.16,
    comboPopDurationMs: 115,
  },
  levelUp: {
    backdropAlpha: 0.9,
    panelAlpha: 0.96,
    optionFillAlpha: 0.68,
    optionStrokeAlpha: 0.58,
  },
  effects: {
    maxParticles: 260,
    enemyBurstParticles: 10,
    enemyBurstSpeedMin: 120,
    enemyBurstSpeedMax: 290,
    enemyBurstLifeMs: 330,
    enemyShardAlpha: 0.72,
    enemyFlashDurationMs: 75,
    enemyFlashScale: 1.22,
    enemyFlashFillAlpha: 0.52,
    enemyFlashStrokeAlpha: 0.94,
    maxTrailSegments: 180,
    orbTrailLifeMs: 210,
    coreAbsorbGlowDurationMs: 145,
    coreAbsorbGlowRadius: 48,
    coreAbsorbGlowAlpha: 0.36,
    coreAbsorbGlowScale: 1.45,
    pulseRingDurationMs: 420,
    pulseRingDurationStepMs: 20,
    pulseEchoDelayMs: 32,
    pulseRingAlpha: 0.38,
    pulseRingChargeAlpha: 0.12,
    pulseRingAlphaStep: 0.07,
    pulseRingInnerAlphaMultiplier: 0.45,
    pulseRingRadiusStep: 14,
    pulseRingStartStep: 8,
    pulseRingWidthChargeBoost: 1.3,
    shockwaveRingDurationMs: 260,
    shockwaveRingAlpha: 0.34,
    shockwaveRingWidth: 1,
  },
} as const;
